### ISSUE TITLE
Suggestion: decouple (de)serialization

### ISSUE THREAD

**Issue by axefrog** [mdesalvo/RDFSharp#1]
Hi, I've noticed a number of tight couplings in your library which make it harder to work with. One such coupling is that of serialization with file access. In my case, I have an ontology as text in a stream and I want to deserialize it so that I can convert it to another format, but the library only supports deserialization from a file. A better approach would be to separate deserialization using some kind of reader/writer implementation, or simply just using streams, and then the deserialization could be used in scenarios where the text comes from the database, from an HTTP call or otherwise.

**Comment by mdesalvo** [comment]
I'm sorry you have encountered a blocking use case in your scenario. You suggest a nice idea, it would be useful to support non file-based serializations, expecially in Web contexts: the approach of the stream should be fine. I'll consider adding an overload of "ReadRDF" method to support this.

Can you kindly share other couplings you have found? I'm open to suggestions.
Regards,
Marco

**Comment by mdesalvo** [comment]
Finalized in commit #b59a4be82376575e202ff5469048225171ca0a1c.
Will be available in 0.8.5 release.
