### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by OscarPDR** [mdesalvo/RDFSharp#141]
I'm trying to validate RDF using a SHACL shape. I have the following two definitions for the data (turtle format):

```
@prefix ex: <http://example.com/ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:peter
	a foaf:Person ;
	foaf:age 20 .
```
and
```
@prefix ex: <http://example.com/ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:peter
	a foaf:Person ;
	foaf:age "twenty".
```

To be matched against the shape (in turtle also):
```
@prefix ex: <http://example.com/ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

ex:PersonShape
    a sh:NodeShape  ;
    sh:targetClass foaf:Person ;
    sh:property [
        sh:path foaf:age ;
        sh:datatype xsd:integer ;
        sh:maxCount 1 ;
        sh:minCount 1 ;
    ] .
```

To validate both data examples I use the following approach:

```
RDFGraph dataGraph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.Turtle, dataFilePath);
RDFGraph rawShapeGraph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.Turtle, shapeFilePath);

RDFShapesGraph shapeGraph = RDFShapesGraph.FromRDFGraph(rawShapeGraph);

var vReport = shapeGraph.Validate(dataGraph);

bool isValid = vReport.Conforms;
```

However, both ot the data samples return a "True", when the second example should not comply due to the _"twenty"_ and _datatype == xsd:integer_ rule for _foaf:age_.

Any thoughts on this?

**Comment by mdesalvo** [comment]
Hi Oscar,
thanks for the report! 

Your case evidenced a glitch in the shapesGraph building procedure: it contains the node shape, but not the linked property shape which is inlined through an anonymous node.

As a workaround you may try to use a slightly more verbose shapegraph like this:

```
@prefix ex: <http://example.com/ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

ex:PersonShape
    a sh:NodeShape  ;
    sh:targetClass foaf:Person ;
    sh:property ex:MyPropertyShape .

ex:MyPropertyShape
    a sh:PropertyShape  ;
    sh:path foaf:age ;
    sh:datatype xsd:integer ;
    sh:maxCount 1 ;
    sh:minCount 1 .
```

Let me know if this helps you at reaching your goal. 
Anyway I'll design a fix to also properly parse the syntax of your case.

Regards,
Marco

**Comment by OscarPDR** [comment]
The workaround works properly, thanks for the quick reply.

Hope you have it solved in the following release, and thank you for your efforts.
