### ISSUE TITLE
Accession of Data in a RDFOntology

### ISSUE THREAD

**Issue by Joott** [mdesalvo/RDFSharp#151]
I have a question about the accession of the data written in a RDFOntology. The Ontology representation is obtained by loading a RDFGraph.
`let graph = RDFSharp.Model.RDFGraph.FromFile (Model.RDFModelEnums.RDFFormats.RdfXml, @"path")`
`let ont = RDFOntology.FromRDFGraph(graph)`
By calling `ont.Data` i get a sequence of the data contained in the ontology, but what it seems to be missing are the properties assigned to the data. Is there a way to obtain all the data of an ontology with the corresponding properties? Thanks in advance for any help!

**Comment by mdesalvo** [comment]
Hi Jonathan,
ont.Data has a **Relations** property which contains links between facts and model classes (ClassType) and also between facts (SameAs, DifferentFrom). You can also access the A-BOX with **ont.Data.Relations.Assertions** and iterate entries or filter them by subject/predicate/object. If you also need annotations, there is **Ont.Data.Annotations** with its properties.

**Comment by Joott** [comment]
Yes, the data in there is what i needed, thank you! Just out of interest, is it possible to get a typed representation of a fact in an ontology, which includes all the information associated with this fact directly (like properties, annotations) without iterating over the different entries in different categories?

**Comment by mdesalvo** [comment]
Sure. In this new kind of object, would you expect to have only explicit knowledge or also inferences available at the moment?

**Comment by Joott** [comment]
I think I would primarily expect explicit facts in such an object. But inferred knowledge would certainly be helpful, if it is distinguishable from explicit knowledge.
This addition would be a great help, thank you very much!

**Comment by mdesalvo** [comment]
Will be available in next release (v2.20)
