### ISSUE TITLE
RDFSharp 2.2.0 hangs parsing turtle file

### ISSUE THREAD

**Issue by oising** [mdesalvo/RDFSharp#154]
The parser hangs with https://brickschema.org/schema/1.1/Brick.ttl

I tried remote uri first, then tested with local copy in case it was a network issue. The same turtle file parses fine in TopBraid and Protege.

**Comment by mdesalvo** [comment]
Triage: Parsed **24309** triples in **7min** (rate: 57.87 triples/sec)
Actions: Profiler session for detecting improvement points in Turtle parser

**Comment by mdesalvo** [comment]
Analysis: Profiler session detected **99.53%** of time spent in **RDFTurtle.ReadCodePoint@310,316** due to usage of **turtleData.ElementAt(index)** to access current buffer character. 
Proposal: Change _turtleData.ElementAt(index)_ to _turtleData.[int index]_
