### ISSUE TITLE
Is there any documentation available?

### ISSUE THREAD

**Issue by ansarizafar** [mdesalvo/RDFSharp#156]
Is it possible to use rdfsharp as a database? Where is the documantation?

**Comment by mdesalvo** [comment]
Hi Zafar,
you can store RDF data on many RDBMS thanks to [extensions](https://github.com/mdesalvo/RDFSharp.Extensions): just include the desired NuGet (6 available: Firebird, MySQL, PostgreSQL, SQLite, SQLServer, Oracle), instantiate its implementation of **RDFStore** and you are ready for storage and querying within your RDFSharp application. 

The [documentation](https://github.com/mdesalvo/RDFSharp/releases/download/v2.20.0/RDFSharp-2.20.0.pdf) has a section explaining usage of stores and structure of the _Quadruples_ table which is automatically handled.
