### ISSUE TITLE
[QUESTION]Mapping concepts between different concept schemes in SKOS

### ISSUE THREAD

**Issue by Joott** [mdesalvo/RDFSharp#157]
As far as i have seen i can map different concepts within the same concept scheme using the `RDFSKOSHelper` like this:
`SKOS.RDFSKOSHelper.AddExactMatchRelation(scheme,concept1,concept2)`
This method only takes one concept scheme as input, therefore mapping concepts from two different concept schemes does not work using this function. I tried adding concepts from two different schemes while only giving one scheme to the method, which resulted in the concept from the different scheme being added to the given scheme, where the mapping relation was then stored. Since this can be expected from this method, i wanted to ask if there is another way to add mapping relations to concepts in two different schemes? Thanks you for your help!

**Comment by mdesalvo** [comment]
Hi Jonathan,
the SKOS API helps at modeling concept schemes by providing an abstraction level over ontologies: in fact its language is made of concepts, concept schemes and labels rather than raw classes, properties and facts. 

When you have modeled your schemes, each own with proper concepts, annotations and relations, you can transform them in RDFOntologyData instances and then merge into a final SKOS-enabled ontology:
```
RDFConceptScheme animals_scheme = new RDFConceptScheme(new RDFResource("http://myskosontology/scheme/animals_scheme"));
RDFConcept cat_concept = new RDFConcept(new RDFResource("http://myskosontology/schemes/animals_scheme/cat_concept"));
RDFConcept dog_concept = new RDFConcept(new RDFResource("http://myskosontology/schemes/animals_scheme/dog_concept"));
animals_scheme.AddConcept(cat_concept);
animals_scheme.AddConcept(dog_concept);

RDFConceptScheme felines_scheme= new RDFConceptScheme(new RDFResource("http://myskosontology/schemes/felines_scheme"));
RDFConcept feline_cat_concept = new RDFConcept(new RDFResource("http://myskosontology/schemes/felines_scheme/feline_cat_concept"));
RDFConcept feline_leopard_concept = new RDFConcept(new RDFResource("http://myskosontology/schemes/felines_scheme/feline_leopard_concept")); 
felines_scheme.AddConcept(feline_cat_concept);
felines_scheme.AddConcept(feline_leopard_concept);

//Just link concepts in one of the schemes
animals_scheme.AddExactMatchRelation(cat_concept, feline_cat_concept);

//Export schemes into ontology data
RDFOntologyData animalsOntology = animals_scheme.ToRDFOntologyData();
RDFOntologyData felinesOntology = felines_scheme.ToRDFOntologyData();

//Build final SKOS ontology
RDFOntology mySkosOntology = new RDFOntology(new RDFResource("http://myskosontology/"));
mySkosOntology.Data = animalsOntology.UnionWith(felinesOntology);
mySkosOntology.Merge(RDFSKOSOntology.Instance); //Support SKOS T-BOX
```

Let me know if this helps at claryfing the picture.
Regards,
Marco

**Comment by Joott** [comment]
Yes, this partly solves my problem, thank you! The problem that still remains for me however, is that the concept that was not part of the scheme in which the relation was added gets added to that concept as well.
```
  <rdf:Description rdf:about="http://myskosontology/schemes/felines_scheme/feline_cat_concept">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept" />
    <skos:inScheme rdf:resource="http://myskosontology/scheme/animals_scheme" />
    <skos:exactMatch rdf:resource="http://myskosontology/schemes/animals_scheme/cat_concept" />
    <skos:inScheme rdf:resource="http://myskosontology/schemes/felines_scheme" />
  </rdf:Description>

  <rdf:Description rdf:about="http://myskosontology/schemes/animals_scheme/cat_concept">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept" />
    <skos:inScheme rdf:resource="http://myskosontology/scheme/animals_scheme" />
    <skos:exactMatch rdf:resource="http://myskosontology/schemes/felines_scheme/feline_cat_concept" />
  </rdf:Description>
```
In the example you posted the concept "feline_cat_concept" is now part of both schemes, while the "cat_concept" is only part of the "animals_scheme" scheme. When the relation is added in the other scheme, the situation is simply reversed. As far as I understood, it should be possible to add relations of concepts between schemes without adding one of the concepts to the other scheme, or am I mistaken there? Thanks for your help!

**Comment by mdesalvo** [comment]
This is due to the behavior of RDFSKOSHelper methods which try to also add the passed concepts to the working scheme before adding the relation:
```
public static RDFSKOSConceptScheme AddExactMatchRelation(this RDFSKOSConceptScheme conceptScheme,
                                                                 RDFSKOSConcept aConcept,
                                                                 RDFSKOSConcept bConcept)
        {
            if (conceptScheme != null && aConcept != null && bConcept != null && !aConcept.Equals(bConcept))
            {
                if (RDFSKOSChecker.CheckCloseOrExactMatchRelation(conceptScheme, aConcept, bConcept))
                {

                    //Add concepts to the scheme
                    conceptScheme.AddConcept(aConcept);
                    conceptScheme.AddConcept(bConcept); //this is addition of feline_cat_concept

                    //Add skos:exactMatch relation to the scheme
                    conceptScheme.Relations.ExactMatch.AddEntry(new RDFOntologyTaxonomyEntry(aConcept, RDFVocabulary.SKOS.EXACT_MATCH.ToRDFOntologyObjectProperty(), bConcept));
                    conceptScheme.Relations.ExactMatch.AddEntry(new RDFOntologyTaxonomyEntry(bConcept, RDFVocabulary.SKOS.EXACT_MATCH.ToRDFOntologyObjectProperty(), aConcept)
                                                      .SetInference(RDFSemanticsEnums.RDFOntologyInferenceType.API));

                }
            }
            return conceptScheme;
        }
```

Thanks for the detailed report. I'll make a fix for this to not add concepts along with their relation anymore: cocnepts will be added only with explicit method **AddConcept**.

Thanks,
Marco
