### ISSUE TITLE
"HasSelf" entailment

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#169]
Hi Marco,
i hope i'm not too active here :)

One more OWL-DL feature which would be useful as reasoner rule:
similar to "hasValue" entailment but based on "hasSelf" restriction.

Turtle files:
[HasSelf.zip](https://github.com/mdesalvo/RDFSharp/files/5982213/HasSelf.zip)

The pretty old usage example:
https://stackoverflow.com/questions/16989042

(And could you help me: are there examples of custom reasoner rules code somewhere? 
I had looked base rules code for the starting point, but they actively use internal classes and methods.)

**Comment by mdesalvo** [comment]
Sure. Thanks for the ttl example, it explains well the concept behind this new OWL-DL rule candidate.

Sorry for the custom rules not being so smart to code (due to usage of library internals being a reserved optimization trick).
Let me explain anatomy of a tipical custom rule. Suppose we want to model a rule emitting data inferences in the form of assertions "FriendOf(**x**, Harry) && IsA(**x**, Wizard) => FriendOf(**x**, Ron)":

```
/// <summary>
/// WizardFriendsOfHarryAreAlsoFriendsOfRon implements data entailments based on the following logics:<br/>
/// ((F1 FRIENDOF HARRY) AND (F1 TYPE WIZARD)) => (F1 FRIENDOF RON)
/// </summary>
internal static RDFOntologyReasonerReport WizardFriendsOfHarryAreAlsoFriendsOfRon(RDFOntology ontology, Dictionary<string, List<RDFOntologyResource>> caches = null)
{
	//[Mandatory] Declare the reasoner report which will be filled by the rule
	var report = new RDFOntologyReasonerReport();

	//Declare modeling facilities used within the rule (facts, properties, classes, etc...)
	var harry = new RDFOntologyFact(new RDFResource("http://myontology/data/facts/harry"));
	var ron = new RDFOntologyFact(new RDFResource("http://myontology/data/facts/ron"));
	var friendOf = new RDFOntologyObjectProperty(new RDFResource("http://myontology/model/properties/friendOf"));
	var wizard = new RDFOntologyClass(new RDFResource("http://myontology/model/classes/Wizard"));

        //Here we use the classmodel reasoner to get subclasses of "Wizard"
	var wizardCompatibleClasses = ontology.Model.ClassModel.GetSubClassesOf(wizard);

	//Filter knowledge: assertions in the form "X friendOf harry"
	foreach (var asn in ontology.Data.Relations.Assertions.SelectEntriesByPredicate(friendOf)
														  .SelectEntriesByObject(harry))
	{
		//Check current knowledge candidate: reason for answering if "X type Wizard"
		bool isWizardFriendOfHarry = ontology.CheckIsMemberOf((RDFOntologyFact)asn.TaxonomySubject, wizard);
		if (isWizardFriendOfHarry)
		{
			//[Mandatory] Create the inference as a taxonomy entry
			var sem_inf = new RDFOntologyTaxonomyEntry((RDFOntologyFact)asn.TaxonomySubject, friendOf, ron).SetInference(RDFSemanticsEnums.RDFOntologyInferenceType.Reasoner);

			//[Mandatory] Add the inference to the report with this check pattern
			if (!ontology.Data.Relations.Assertions.ContainsEntry(sem_inf))
				report.AddEvidence(new RDFOntologyReasonerEvidence(RDFSemanticsEnums.RDFOntologyReasonerEvidenceCategory.Data, nameof(WizardFriendsOfHarryAreAlsoFriendsOfRon), nameof(RDFOntologyData.Relations.Assertions), sem_inf));

		}
	}

	//[Mandatory] Return the reasoner filled with evidences
	return report;
}
```

Let me know if this basic example is clear. Of course you may have more advanced reasoning needs, so if you encounter troubles in traducing your reasoning ideas feel free to write them.

Regards,
Marco

**Comment by constnick** [comment]
Thanks for this example, it's helpful.

But it uses internal ctors:
```
RDFOntologyReasonerReport
RDFOntologyTaxonomyEntry
RDFOntologyReasonerEvidence
```
and methods
```
SetInference
ContainsEntry
AddEvidence
```
and so it can't be defined outside of RDFSharp?

**Comment by mdesalvo** [comment]
It seems many methods useful in the context of custom rule modeling are internal. I'll check for ones suitable for public opening.

**Comment by constnick** [comment]
And about "inverseOf" for property chains (sorry for oftop here, i've commented in related closed issue, but that comment can be lost).

The point is that some existing ontologies may rely on this feature, because well-known reasoners allow it, and this is my case.

May be, it would be possible to implement this rule, but disable by default, and allow user to enable it explicitly.

**Comment by mdesalvo** [comment]
I'll see a way to accomplish this.
