### ISSUE TITLE
Reading single ontology from several files

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#173]
Hi Marco,
what is the right way to do it (concerning correctness and performance)?
First read graphs from each file, then

- union them to one graph with `RDFGraph.UnionWith`, then make ontology from it; 
or
- make ontology from each graph, then merge them all with `RDFOntology.Merge`?

(Files contain parts of single ontology, for example model, data, shapes in separate files with import declarations.)

**Comment by mdesalvo** [comment]
Hi,
I suggest the first approach. Get a unique graph and go with the ontology parsing process.

**Comment by constnick** [comment]
Thanks!
