### ISSUE TITLE
Using ToRDFOntologyObjectProperty() and others of RDFSemanticsUtilities

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#175]
Hi Marco,

when in custom reasoner rule i need some standard predicate (e.g. `rdf:type`) for new axiom, i can't use `RDFVocabulary.RDF.TYPE.ToRDFOntologyObjectProperty()` because class `RDFSemanticsUtilities` is internal.

Or is there another correct way to obtain standard predicates?

**Comment by mdesalvo** [comment]
Hi,
I'll open these methods in a public extension class in the next release. 
In the meanwhile the quickest solution is to replicate their behavior, they're just one liners in most cases:
```
RDFOntologyObjectProperty typeProperty = new RDFOntologyObjectProperty(RDFVocabulary.RDF.TYPE);
```

Regards,
Marco
