### ISSUE TITLE
Iterated reasoning

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#176]
Hi Marco,

In some cases single applying of the reasoner don't emit all assumed axioms, and several consecutive applyings required.
Examples:
[TTL.zip](https://github.com/mdesalvo/RDFSharp/files/6109113/TTL.zip)

Currently I apply reasoner in loop with checking whether new axioms was added to ontology.
May be it would be more efficient to implement some kind of more sophisticated approach in `RDFOntologyReasoner` class itself?

**Comment by mdesalvo** [comment]
Hi,
starting from v2.21 the reasoner works on the ontology without materialization: inferences are collected from the execution of chosen rules, then it's up to you opting for enriching the knowledge base or just presenting them into your application UI. This can be done in an iterative process handled by your application (as you are perfectly doing): you'll notice an incremental discovery at each iteration, at the predictable cost of increasing computation effort. 
Being this the standard behavior for non-materializing reasoners, it's hard to imagine a more sophisticated approach without implying a partial or complete rewriting of RDFSharp.Semantics layer.

Regards,
Marco

**Comment by constnick** [comment]
OK, thanks!
