### ISSUE TITLE
The code in manual makes compile error

### ISSUE THREAD

**Issue by felinepunch** [mdesalvo/RDFSharp#177]
In RDFSharp-2.22.0.pdf at page 5, there is a incorrect code. This code makes compile error.

// CREATE GRAPH FROM A LIST OF TRIPLES
var triples = new List<RDFTriple>({mickeymouse_is85yr, donaldduck_name_enus});

var triples = new List<RDFTriple>{mickeymouse_is85yr, donaldduck_name_enus};
is correct syntax.

**Comment by felinepunch** [comment]
I found more.
At page 24, the constructor of RDFMemoryStore has no arguments. So this code makes compile error.

// CREATE MEMORY STORE FROM A LIST OF QUADRUPLES
var wdStoreFilled = new RDFMemoryStore(new List<RDFQuadruple>({wk_mickeymouse_is85yr,
wk_mickeymouse_is85yr));

and 
Console.Writeline method is not exist.
Console.WriteLine is correct method.

**Comment by mdesalvo** [comment]
Hi,
thanks for the report. 

I'll republish the documentation with the reported fixes.

Regards,
Marco
