### ISSUE TITLE
Getting 'TaxonomyEntry' by ID

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#181]
Hi Marco
Isn't it possible to get `RDFOntologyTaxonomyEntry` from `RDFOntologyTaxonomy` by `TaxonomyEntryID`?
The only way I see currently is to iterate over all entries and check IDs.

**Comment by mdesalvo** [comment]
Sure,
this can be added in the next version.

**Comment by constnick** [comment]
Ok, great!

And minor typo in code:
```c#
/// <summary>
/// RDFOntologyTaxonomy represents an entry of a RDFOntologyTaxonomy object.
/// </summary>
public class RDFOntologyTaxonomyEntry : IEquatable<RDFOntologyTaxonomyEntry>
```
Apparently would be `/// RDFOntologyTaxonomyEntry represents ...`
