### ISSUE TITLE
Getting type for datatype property

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#184]
Hi Marco,
I've not found a smart way to get the datatype (`RDFModelEnums.RDFDatatypes`) for the `Range` of given `RDFOntologyDatatypeProperty`.
Is it possible?
(For example if we need a new assertion with given property, we have to know correct datatype to create a typed literal as it's object. Or i missed something again?)

**Comment by mdesalvo** [comment]
Hi,
it seems the method you need for dealing with datatype<->string conversions is internal. I'll open this in the next release, it will be usable like this:

```
if (datatypeProperty.Range != null)
    RDFModelEnums.RDFDatatypes datatypePropertyRangeDatatype = RDFModelUtilities.GetDatatypeFromString(datatypeProperty.Range.ToString());
```

**Comment by constnick** [comment]
OK, thanks!
