### ISSUE TITLE
Replace individual (aka fact)

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#187]
Hi, Marco,
is it possible to replace totally any given individual (instance of `RDFOntologyFact`) with another one within an instance of `RDFOntologyData`?

**Comment by mdesalvo** [comment]
Hi,
this is not possible at the moment. Anyway I can think about an extension method of RDFOntologyData which would act like the renaming feature of Protege: every occurrence of the fact would be replaced by the new fact (assertions, negativeassertions, sameas, differentfrom, classtype, annotations). I'll do in the next version.

**Comment by constnick** [comment]
Great, It will be helpful, thanks
