### ISSUE TITLE
RDFSharp.RDFSQLiteStore?

### ISSUE THREAD

**Issue by JimSEOW** [mdesalvo/RDFSharp#22]
What happened to this?

**Comment by mdesalvo** [comment]
Dear JimSEOW,
the source code of the store plugins (SQLite, Firebird, MySQL, PostgreSQL) is available in the download page of the latest release. If you mean their project pages, they have been retired from GitHub/Codeplex.

Best regards,
Marco

**Comment by JimSEOW** [comment]
Thanks. This really help!
