### ISSUE TITLE
RDFOntologyFact within RDFOntologyData 

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#236]
I need to know whether an instance of `RDFOntologyData ` contains the given instance of `RDFOntologyFact `.
There is `SelectFact` method which requires a string, but it would be better and faster in some cases to use ID or the instance itself, without redundant string operations.
Maybe a public method just checking the internal dictionary `Facts` would be useful?

**Comment by mdesalvo** [comment]
Sure. An overload of SelectFact taking the ID is quicker.
