### ISSUE TITLE
Annotations of Axioms

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#237]
Hi Marco!
Doesn't RDFSharp supports annotations of axioms?
Turtle example attached (made with Protege).
[TEST.AnnotationsOfAxioms.ttl.txt](https://github.com/mdesalvo/RDFSharp/files/6762048/TEST.AnnotationsOfAxioms.ttl.txt)

**Comment by mdesalvo** [comment]
Hi,
I marked axiom annotation as a low priority _nice to have_ feature at the time of OWL2 project inception. Sure it can be quite easily realized by supporting another kind of TaxonomyEntry in OntologyData annotations, but at the moment I can't assign a precise project milestone: all development efforts are on the new SWRL semantics layer.

**Comment by constnick** [comment]
OK, thanks!
It's not critical, so it was just a question :)

**Comment by mdesalvo** [comment]
Limits of the current architecture permit only to model axiom annotations for assertions
