### ISSUE TITLE
[BUG] Validating `sh:path` containing `sh:inversePath` not working.

### ISSUE THREAD

**Issue by Pingviinituutti** [mdesalvo/RDFSharp#302]
**Describe the bug**
It seems that SHACL shapes with `sh:inversePath` are not working as they should be. A correctly set cardinality with `sh:inversePath` triggers an error with RDFSharp.

**Expected behavior**
Link to [SHACL Playground](https://shacl-playground.zazuko.com/#page=1&shapesGraph=%40prefix+ex%3A+++++%3Chttp%3A%2F%2Fexample.com%2Fns%23%3E+.%0A%40prefix+rdf%3A+++++%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+sh%3A++++++%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0Aex%3AParent++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AParent.Child-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AParent+.%0A%0A%0Aex%3AChild++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AChild.Parent-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AChild+.%0A%0Aex%3AParent.Child-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+Lower+bound+shall+be+1.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++%5B+sh%3AinversePath++ex%3AChild.Parent+%5D+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A%0Aex%3AChild.Parent-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+A+child+should+have+at+least+one+parent.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++ex%3AChild.Parent+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A&shapesGraphFormat=text%2Fturtle&dataGraph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3Crdf%3ARDF%0A++++xml%3Abase%3D%22http%3A%2F%2Fexample.com%2Fns%22%0A%09xmlns%3Ardf%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%0A%09xmlns%3Aex%3D%22http%3A%2F%2Fexample.com%2Fns%23%22%0A%09%3E%0A%0A%09%3Cex%3AChild+rdf%3Aabout%3D%22child%22%3E%0A%09%09%3Cex%3AChild.Parent+rdf%3Aresource%3D%22parent0%22+%2F%3E%0A%09%3C%2Fex%3AChild%3E%0A%0A%09%3Cex%3AParent+rdf%3Aabout%3D%22parent0%22%3E%0A++++%3C%2Fex%3AParent%3E%0A%0A%09%3Cex%3AParent+rdf%3Aabout%3D%22parent1%22+%2F%3E%0A%3C%2Frdf%3ARDF%3E&dataGraphFormat=application%2Frdf%2Bxml).

In this parent-child relationship, there is a requirement for a child to have at least one parent and each parent to have at least one child. The catch here is that the `Parent.Child` cardinality is constrained as `sh:path  [ sh:inversePath  ex:Child.Parent ] ;`.
The expected behaviour is that only the `ex:Parent` instance `parent1` should raise an error. However, both `parent0` and `parent1` instances trigger the error when running the minimal working example below. The SHACL Playground (linked above) shows correct behaviour.

**Library Version**
`RDFSharp version '3.5.0'`

**Additional context**
Minimal working example:

``` ttl
// shapedata-parent-child.xml
@prefix ex:     <http://example.com/ns#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .

ex:Parent  rdf:type  sh:NodeShape ;
        sh:property     ex:Parent.Child-cardinality ;
        sh:targetClass  ex:Parent .


ex:Child  rdf:type  sh:NodeShape ;
        sh:property     ex:Child.Parent-cardinality ;
        sh:targetClass  ex:Child .

ex:Parent.Child-cardinality
        rdf:type        sh:PropertyShape ;
        sh:description  "This constraint validates the cardinality of the association at the inverse direction." ;
        sh:group        ex:CardinalityGroup ;
        sh:message      "Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality" ;
        sh:minCount     1 ;
        sh:name         "Parent.Child-cardinality" ;
        sh:order        0 ;
        sh:path         [ sh:inversePath  ex:Child.Parent ] ;
        sh:severity     sh:Violation .

ex:Child.Parent-cardinality
        rdf:type        sh:PropertyShape ;
        sh:description  "This constraint validates the cardinality of the association at the inverse direction." ;
        sh:group        ex:CardinalityGroup ;
        sh:message      "Cardinality violation. A child should have at least one parent. ex:Parent.Child-cardinality" ;
        sh:minCount     1 ;
        sh:name         "Parent.Child-cardinality" ;
        sh:order        0 ;
        sh:path         ex:Child.Parent ;
        sh:severity     sh:Violation .
```

``` xml
<!-- shapedata-parent-child.xml -->
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:ex="http://example.com/ns#"
	>

	<ex:Child rdf:about="http://example.com/child">
		<ex:Child.Parent rdf:resource="http://example.com/parent0" />
	</ex:Child>

	<ex:Parent rdf:about="http://example.com/parent0">
    </ex:Parent>

	<ex:Parent rdf:about="http://example.com/parent1" />
</rdf:RDF>

```

``` cs
// See https://aka.ms/new-console-template for more information
using RDFSharp.Model;
using System;
using System.Text;

string shapesValidationFilePath = "SHACL_constraints_parent_child.ttl";
string dataFilePath = "shapedata-parent-child.xml";

try
{
    RDFGraph dataGraph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.RdfXml, dataFilePath);

    RDFGraph shapesGraphObject = RDFGraph.FromFile(
        RDFModelEnums.RDFFormats.Turtle,
        shapesValidationFilePath
    );
    RDFShapesGraph shapesGraphValidation = RDFShapesGraph.FromRDFGraph(shapesGraphObject);
    //validate
    StringBuilder sb = new StringBuilder();
    RDFValidationReport validationResults = shapesGraphValidation.Validate(dataGraph);
    if (!validationResults.Conforms)
    {
        foreach (RDFValidationResult result in validationResults)
        {
            foreach (RDFLiteral resultMessage in result.ResultMessages)
            {
                sb.AppendLine(result.ResultPath.URI.Fragment + " " + resultMessage.ToString() + ". ID: " + result.FocusNode.ToString());
            }
        }
        Console.WriteLine("RDFSharp Validation errors:");
        string errors = sb.ToString();
        Console.WriteLine(errors);
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

Result
```
RDFSharp Validation errors:
 Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality. ID: http://example.com/parent0
 Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality. ID: http://example.com/parent1
```

**Comment by mdesalvo** [comment]
Thanks Henrik for the very detailed and precise report.

I'll investigate about this and post updates here.

Regards,
Marco

**Comment by mdesalvo** [comment]
Hi Henrik,
I merged the work for proper detection and handling of "sh:path" declared with "sh:inversePath", which should allow you to successfully deal with this use case. It was my glitch to not know this kind of syntax.

Expect a new release containing the feature in the next days.

Thanks again and regards,
Marco

**Comment by Pingviinituutti** [comment]
Wow that was quick! Thank you very much! Much appreciated!
