### ISSUE TITLE
[BUG] Validation of `sh:path` with `sh:alternativePath` not working per the SHACL spec

### ISSUE THREAD

**Issue by Pingviinituutti** [mdesalvo/RDFSharp#304]
**Describe the bug**
It seems that `sh:alternativePath` is not working according to the [SHACL spec](https://www.w3.org/TR/shacl/#property-path-alternative).

**Expected behavior**
Link to [SHACL Playground](https://shacl-playground.zazuko.com/#page=1&shapesGraph=%40prefix+ex%3A+++++%3Chttp%3A%2F%2Fexample.com%2Fns%23%3E+.%0A%40prefix+rdf%3A+++++%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+sh%3A++++++%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0Aex%3APerson++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3APerson.mobile-landline-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3APerson+.%0A%0Aex%3APerson.mobile-landline-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+that+a+Person+has+either+mobileNumber+or+landLine+set.%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Amessage++++++%22Either+mobileNumber+or+landLine+should+be+present%22+%3B%0A++++++++sh%3Aname+++++++++%22Person.mobileNumber-landLine-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++%5B+sh%3AalternativePath+%28+ex%3APerson.mobilePhone+ex%3APerson.landLine+%29+%5D+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A%0A%0A&shapesGraphFormat=text%2Fturtle&dataGraph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3Crdf%3ARDF%0A%09xmlns%3Ardf%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%0A%09xmlns%3Aex%3D%22http%3A%2F%2Fexample.com%2Fns%23%22%0A%09%3E%0A%0A%09%3Cex%3APerson+rdf%3Aabout%3D%22http%3A%2F%2Fexample.com%2Fns%23person0%22%3E%0A++++++++%3Cex%3APerson.mobilePhone%3E0123456789%3C%2Fex%3APerson.mobilePhone%3E%0A++++%3C%2Fex%3APerson%3E%0A%0A%09%3Cex%3APerson+rdf%3Aabout%3D%22http%3A%2F%2Fexample.com%2Fns%23person1%22%3E%0A++++++++%3Cex%3APerson.landLine%3E0123456789%3C%2Fex%3APerson.landLine%3E%0A++++%3C%2Fex%3APerson%3E%0A%0A%09%3Cex%3APerson+rdf%3Aabout%3D%22http%3A%2F%2Fexample.com%2Fns%23person2%22%3E%0A++++++++%3Cex%3APerson.mobilePhone%3E0123456789%3C%2Fex%3APerson.mobilePhone%3E%0A++++++++%3Cex%3APerson.landLine%3E0123456789%3C%2Fex%3APerson.landLine%3E%0A++++%3C%2Fex%3APerson%3E%0A%0A%09%3Cex%3APerson+rdf%3Aabout%3D%22http%3A%2F%2Fexample.com%2Fns%23person3%22%3E%0A++++%3C%2Fex%3APerson%3E%0A%3C%2Frdf%3ARDF%3E&dataGraphFormat=application%2Frdf%2Bxml)

`sh:alternativePath` should basically be an _or_ to check that either one (or both) of the given paths should exist. So in this case for a `ex:Person` with `sh:path  [ sh:alternativePath ( ex:Person.mobilePhone ex:Person.landLine ) ] `, either the path `ex:Person.MobilePhone` or the path `ex:Person.landLine` should be given.

The issue is that RDFSharp triggers an `sh:Violation` for every a person with or without the any of the given paths.

**Library Version**
`RDFSharp version '3.5.0'`

**Additional context**
Minimal working example:

```  
# SHACL_constraints_person.ttl
@prefix ex:     <http://example.com/ns#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .

ex:Person  rdf:type  sh:NodeShape ;
        sh:property     ex:Person.mobile-landline-cardinality ;
        sh:targetClass  ex:Person .

ex:Person.mobile-landline-cardinality
        rdf:type        sh:PropertyShape ;
        sh:description  "This constraint validates that a Person has either mobileNumber or landLine set." ;
        sh:minCount     1 ;
        sh:message      "Either mobileNumber or landLine should be present" ;
        sh:name         "Person.mobileNumber-landLine-cardinality" ;
        sh:order        0 ;
        sh:path         [ sh:alternativePath ( ex:Person.mobilePhone ex:Person.landLine ) ] ;
        sh:severity     sh:Violation .
```

``` 
<!-- person.xml -->
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:ex="http://example.com/ns#"
	>

	<ex:Person rdf:about="http://example.com/ns#person0">
        <ex:Person.mobilePhone>0123456789</ex:Person.mobilePhone>
    </ex:Person>

	<ex:Person rdf:about="http://example.com/ns#person1">
        <ex:Person.landLine>0123456789</ex:Person.landLine>
    </ex:Person>

	<ex:Person rdf:about="http://example.com/ns#person2">
        <ex:Person.mobilePhone>0123456789</ex:Person.mobilePhone>
        <ex:Person.landLine>0123456789</ex:Person.landLine>
    </ex:Person>

	<ex:Person rdf:about="http://example.com/ns#person3">
    </ex:Person>
</rdf:RDF>
```

``` cs
// Program.cs
using RDFSharp.Model;
using System;
using System.Text;

string shapesValidationFilePath = "SHACL_constraints_person.ttl";
string dataFilePath = "person.xml";

try
{
    RDFGraph dataGraph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.RdfXml, dataFilePath);

    RDFGraph shapesGraphObject = RDFGraph.FromFile(
        RDFModelEnums.RDFFormats.Turtle,
        shapesValidationFilePath
    );
    RDFShapesGraph shapesGraphValidation = RDFShapesGraph.FromRDFGraph(shapesGraphObject);
    //validate
    StringBuilder sb = new StringBuilder();
    RDFValidationReport validationResults = shapesGraphValidation.Validate(dataGraph);
    if (!validationResults.Conforms)
    {
        foreach (RDFValidationResult result in validationResults)
        {
            foreach (RDFLiteral resultMessage in result.ResultMessages)
            {
                sb.AppendLine(result.ResultPath.URI.Fragment + " " + resultMessage.ToString() + ". ID: " + result.FocusNode.ToString());
            }
        }
        Console.WriteLine("RDFSharp Validation errors:");
        string errors = sb.ToString();
        Console.WriteLine(errors);
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```
Results:
```
RDFSharp Validation errors:
 Either mobileNumber or landLine should be present. ID: http://example.com/ns#person0
 Either mobileNumber or landLine should be present. ID: http://example.com/ns#person1
 Either mobileNumber or landLine should be present. ID: http://example.com/ns#person2
 Either mobileNumber or landLine should be present. ID: http://example.com/ns#person3
```
Expected: only `person3` should throw an `sh:Violation`.

**Comment by mdesalvo** [comment]
Hi Henrik,
thanks for the report (precise as usual).

I'm working on this to add support for "sh:alternativePath" syntax and will let you know here the progress.

Regards,
Marco

**Comment by Pingviinituutti** [comment]
Hi Marco!

No problems here! Thanks a bunch for adding the fix :)

Best regards,
Henrik

**Comment by mdesalvo** [comment]
I'm also adding "sh:path (prop1 prop2)" which I saw is the sequential form of paths.

Other variants can't be supported (like the ones stating cardinality with "+" or "*") because unfortunately our algebra is not capable of computing them neither in SPARQL. But, at least, with your support our SHACL engine has improved nicely :)

Thanks and regards,
Marco
