### ISSUE TITLE
[BUG] RDF/XML elements with `rdf:ID` sets subject URI improperly.

### ISSUE THREAD

**Issue by Pingviinituutti** [mdesalvo/RDFSharp#307]
**Describe the bug**
Validating cardinalities on instances defined with `rdf:ID` instead of `rdf:about` is not consistent.

**Expected behavior**
A required child-parent association is expected to validate the same way independently of if the child's or parent's subject URI is set with `rdf:ID` or `rdf:about`. See the shacl playgrounds here:
* data defined with `rdf:ID` [SHACL Playground linke](https://shacl-playground.zazuko.com/#page=1&shapesGraph=%40prefix+ex%3A+++++%3Chttp%3A%2F%2Fexample.com%2Fns%23%3E+.%0A%40prefix+rdf%3A+++++%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+sh%3A++++++%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0Aex%3AParent++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AParent.Child-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AParent+.%0A%0Aex%3AParent.Child-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+Lower+bound+shall+be+1.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++%5B+sh%3AinversePath+ex%3AChild.Parent+%5D+%3B%0A++++++++sh%3AminCount+1+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A%0A%0Aex%3AChild++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AChild.Parent-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AChild+.%0A%0Aex%3AChild.Parent-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+A+child+should+have+at+least+one+parent.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++ex%3AChild.Parent+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A&shapesGraphFormat=text%2Fturtle&dataGraph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3Crdf%3ARDF%0A++++xml%3Abase%3D%22http%3A%2F%2Ftest.com%2F%22%0A%09xmlns%3Ardf%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%0A%09xmlns%3Aex%3D%22http%3A%2F%2Fexample.com%2Fns%23%22%0A%09%3E%0A%0A%09%3Cex%3AChild+rdf%3AID%3D%22child%22%3E%0A%09%09%3Cex%3AChild.Parent+rdf%3Aresource%3D%22%23parent0%22+%2F%3E%0A%09%3C%2Fex%3AChild%3E%0A%0A%09%3Cex%3AParent+rdf%3AID%3D%22parent0%22+%2F%3E%0A%0A%09%3Cex%3AParent+rdf%3AID%3D%22parent1%22+%2F%3E%0A%3C%2Frdf%3ARDF%3E&dataGraphFormat=application%2Frdf%2Bxml)
* data defined with `rdf:about` [SHACL Playground link](https://shacl-playground.zazuko.com/#page=1&shapesGraph=%40prefix+ex%3A+++++%3Chttp%3A%2F%2Fexample.com%2Fns%23%3E+.%0A%40prefix+rdf%3A+++++%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+.%0A%40prefix+sh%3A++++++%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E+.%0A%0Aex%3AParent++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AParent.Child-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AParent+.%0A%0A%0Aex%3AChild++rdf%3Atype++sh%3ANodeShape+%3B%0A++++++++sh%3Aproperty+++++ex%3AChild.Parent-cardinality+%3B%0A++++++++sh%3AtargetClass++ex%3AChild+.%0A%0Aex%3AParent.Child-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+Lower+bound+shall+be+1.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++%5B+sh%3AinversePath++ex%3AChild.Parent+%5D+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A%0Aex%3AChild.Parent-cardinality%0A++++++++rdf%3Atype++++++++sh%3APropertyShape+%3B%0A++++++++sh%3Adescription++%22This+constraint+validates+the+cardinality+of+the+association+at+the+inverse+direction.%22+%3B%0A++++++++sh%3Agroup++++++++ex%3ACardinalityGroup+%3B%0A++++++++sh%3Amessage++++++%22Cardinality+violation.+A+child+should+have+at+least+one+parent.+ex%3AParent.Child-cardinality%22+%3B%0A++++++++sh%3AminCount+++++1+%3B%0A++++++++sh%3Aname+++++++++%22Parent.Child-cardinality%22+%3B%0A++++++++sh%3Aorder++++++++0+%3B%0A++++++++sh%3Apath+++++++++ex%3AChild.Parent+%3B%0A++++++++sh%3Aseverity+++++sh%3AViolation+.%0A&shapesGraphFormat=text%2Fturtle&dataGraph=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22utf-8%22%3F%3E%0A%3Crdf%3ARDF%0A++++xml%3Abase%3D%22http%3A%2F%2Fexample.com%2Fns%22%0A%09xmlns%3Ardf%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%0A%09xmlns%3Aex%3D%22http%3A%2F%2Fexample.com%2Fns%23%22%0A%09%3E%0A%0A%09%3Cex%3AChild+rdf%3Aabout%3D%22%23child%22%3E%0A%09%09%3Cex%3AChild.Parent+rdf%3Aresource%3D%22%23parent0%22+%2F%3E%0A%09%3C%2Fex%3AChild%3E%0A%0A%09%3Cex%3AParent+rdf%3Aabout%3D%22%23parent0%22%3E%0A++++%3C%2Fex%3AParent%3E%0A%0A%09%3Cex%3AParent+rdf%3Aabout%3D%22%23parent1%22+%2F%3E%0A%3C%2Frdf%3ARDF%3E&dataGraphFormat=application%2Frdf%2Bxml)

I noticed that when I added a `#` in front of the `rdf:ID` value, i.e., `#parent0`, then the error did not appear anymore (based on the minimal working example below). It looks like the IRI for an element with `rdf:ID` set is not concatenated with an `#` as described in the [w3c RDF 1.1 XML Syntax recommendations Section 2.14](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-ID-xml-base) (second paragraph)?

**Library Version**
RDFSharp 3.6.0

**Additional context**
Minimal working example.

``` turtle
# SHACL constraints - SHACL_parent_child.ttl
@prefix ex:     <http://example.com/ns#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .

ex:Parent  rdf:type  sh:NodeShape ;
        sh:property     ex:Parent.Child-cardinality ;
        sh:targetClass  ex:Parent .

ex:Parent.Child-cardinality
        rdf:type        sh:PropertyShape ;
        sh:description  "This constraint validates the cardinality of the association at the inverse direction." ;
        sh:group        ex:CardinalityGroup ;
        sh:message      "Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality" ;
        sh:minCount     1 ;
        sh:name         "Parent.Child-cardinality" ;
        sh:order        0 ;
        sh:path     [ sh:inversePath ex:Child.Parent ] ;
        sh:minCount 1 ;
        sh:severity     sh:Violation .


ex:Child  rdf:type  sh:NodeShape ;
        sh:property     ex:Child.Parent-cardinality ;
        sh:targetClass  ex:Child .

ex:Child.Parent-cardinality
        rdf:type        sh:PropertyShape ;
        sh:description  "This constraint validates the cardinality of the association at the inverse direction." ;
        sh:group        ex:CardinalityGroup ;
        sh:message      "Cardinality violation. A child should have at least one parent. ex:Parent.Child-cardinality" ;
        sh:minCount     1 ;
        sh:name         "Parent.Child-cardinality" ;
        sh:order        0 ;
        sh:path         ex:Child.Parent ;
        sh:severity     sh:Violation .
```

``` xml
<!-- data - parent-child.xml -->
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
    xml:base="http://test.com/"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:ex="http://example.com/ns#"
	>

	<ex:Child rdf:ID="child">
		<ex:Child.Parent rdf:resource="#parent0" />
	</ex:Child>

	<ex:Parent rdf:ID="parent0" />

	<ex:Parent rdf:ID="parent1" />

	<ex:Child rdf:about="#child10">
		<ex:Child.Parent rdf:resource="#parent10" />
	</ex:Child>

	<ex:Parent rdf:about="#parent10" />

	<ex:Parent rdf:about="#parent11" />
</rdf:RDF>
```

``` cs
// sample Program.cs
// See https://aka.ms/new-console-template for more information
using RDFSharp.Model;
using System;
using System.Text;

string shapesValidationFilePath = "SHACL_parent_child.ttl";
string dataFilePath = "parent-child.xml";

try
{
    RDFGraph dataGraph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.RdfXml, dataFilePath);

    RDFGraph shapesGraphObject = RDFGraph.FromFile(
        RDFModelEnums.RDFFormats.Turtle,
        shapesValidationFilePath
    );
    RDFShapesGraph shapesGraphValidation = RDFShapesGraph.FromRDFGraph(shapesGraphObject);
    //validate
    StringBuilder sb = new StringBuilder();
    RDFValidationReport validationResults = shapesGraphValidation.Validate(dataGraph);
    if (!validationResults.Conforms)
    {
        foreach (RDFValidationResult result in validationResults)
        {
            foreach (RDFLiteral resultMessage in result.ResultMessages)
            {
                sb.AppendLine(result.ResultPath.URI.Fragment + " " + resultMessage.ToString() + ". ID: " + result.FocusNode.ToString());
            }
        }
        Console.WriteLine("RDFSharp Validation errors:");
        string errors = sb.ToString();
        Console.WriteLine(errors);
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

This outputs
``` sh
DFSharp Validation errors:
#Child.Parent Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality. ID: http://test.com/parent0
#Child.Parent Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality. ID: http://test.com/parent1
#Child.Parent Cardinality violation. Lower bound shall be 1. ex:Parent.Child-cardinality. ID: http://test.com/#parent11
```

It is expected that the element with id `parent0` should not trigger an `sh:Violation`.

**Comment by mdesalvo** [comment]
Hi Henrik,
thanks as usual for the detailed report: it makes me working on the issue at minute 0!

I posted a fix for the incorrect parsing of rdf:ID elements in RDF/XML. Nice catch.
I'll do a bugfix release for this.

Regards,
Marco
