### ISSUE TITLE
https://www.w3.org/XML/1998/namespace# breaks xml compatibility

### ISSUE THREAD

**Issue by norlesh** [mdesalvo/RDFSharp#50]
Hi Marco, firstly thanks for all your hard work. One problem I ran in to however when attempting to load an OWL file written in XML was an exception being thrown due to the base uri for the namespace 'xml' being set to 'https://www.w3.org/XML/1998/namespace#' (from the static XML class located in RDFVocabulary.cs) instead of 'https://www.w3.org/XML/1998/namespace' without the hash symbol. 
As stated in the text readable document located at that uri "The namespace whose name is http://www.w3.org/XML/1998/namespace is bound by definition to the prefix xml: according to Namespaces in XML"

**Comment by mdesalvo** [comment]
Thanks for having catched this long-standing typo. The fix will be available in the next minor release.
Regards,
Marco
