### ISSUE TITLE
Please consider adding a demo project

### ISSUE THREAD

**Issue by sberney** [mdesalvo/RDFSharp#51]
As someone without previous experience with RDF, this project is pretty mysterious. I came here because I have a project in mind, I came across RDF while researching its prerequisites, and I'd be happy to work in C#. However as a neophite I'm not actually 100% sure what this library does. A demo project with a small writeup describing what that demo is doing would go a long way towards illustrating what RDFSharp can do.

Thanks!

**Comment by mdesalvo** [comment]
Thanks for the precious feedback, Sam. 
The demo project is under planning. In the meanwhile I suggest you give a look at the project [RdfDemo](https://github.com/capybara1/RdfDemo), which I consider a nice third-party showcase for the library capabilities (even if not complete). There is also official PDF in latest release: this is the preferred starting point for learning RDF/SPARQL modeling with RDFSharp.

Regards,
Marco
