### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by olesjo** [mdesalvo/RDFSharp#60]
Would have been nice with a sample code to demonstrate how this works.

**Comment by mdesalvo** [comment]
Hi olesjo, thanks for the feedback.
Every release has an updated PDF reference guide explaining all the features, this is the preferred way of starting. There is also a nice project explaining practical modeling and query usages: [RdfDemo](https://github.com/capybara1/RdfDemo).

Regards,
Marco
