### ISSUE TITLE
RDFOntologyDatatypeProperty.SetRange method should require a type instead of a class

### ISSUE THREAD

**Issue by UrielKaralden** [mdesalvo/RDFSharp#80]
Hello there! I'd like to ask you if the method SetRange(RDFOntologyClass rangeClass) implemented in RDFSharp/Semantics/Ontology/Model/PropertyModel/RDFOntologyProperty.cs should have an override version for RDFOntologyDatatypeProperty, as the range of DatatypeProperties are defined as RDFModelEnum.RDFDatatypes, so the method would be: 

`public RDFOntologyProperty SetRange(RDFModelEnums.RDFDatatypes rangeType) {`
`    if (!this.IsAnnotationProperty())`
`       this.Range = rangeType;`
`    return this;`
`}`

For doing this, it would be necessarily to override Range property for RDFOntologyDatatypeProperty, in which case I think is preferrable to define Range property and its methods inside the child classes RDFOntologyObjectProperty and RDFOntologyDatatypeProperty.

If it weren't the case, how can I use SetRange with a defined datatype?

Thank you, 
UrielKaralden #

**Comment by mdesalvo** [comment]
Hi Uriel,
[here](https://github.com/mdesalvo/RDFSharp/files/4350874/GetClassFromDatatype.txt) an example method which gets an ontology class from a datatype enumeration. You could start from it as idea for a _SetRange_ extension method for _RDFOntologyDatatypeProperty_, this way allowing the desired signature to work.

Thanks,
Marco
